name: Build tools and Toolchain
run-name: Build tools and Toolchain - ${{ inputs.config_name }}
on:
  workflow_dispatch:
    inputs:
      repo_url:
        type: string
      repo_branch:
        type: string
      config_name:
        type: string
      use_ccache_cache:
        type: boolean
        default: true
  workflow_call:
    inputs:
      repo_url:
        type: string
      repo_branch:
        type: string
      config_name:
        type: string
      use_ccache_cache:
        type: boolean
        default: true
env:
  REPO_URL: ${{ github.event.inputs.repo_url || 'hanwckf/immortalwrt-mt798x' }}
  REPO_BRANCH: ${{ github.event.inputs.repo_branch || 'openwrt-21.02' }}
  CONFIG_FILE: ${{ github.event.inputs.config_name || '.config7981'}}
jobs:
  determine_targets:
    name: Determine targets
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.find_targets.outputs.target }}
      subtarget: ${{ steps.find_targets.outputs.subtarget }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkoutsrc
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPO_URL }}
        ref: ${{ env.REPO_BRANCH}}
        path: openwrt

    - name: Find targets
      id: find_targets
      run: |
        [[ -d "files" ]] && mv -f files openwrt/files
        [[ -e ${CONFIG_FILE} ]] && cp -f ${CONFIG_FILE} openwrt/.config
        cd openwrt
        make defconfig
        eval "$(grep \
                  -e ^CONFIG_TARGET_BOARD= \
                  -e ^CONFIG_TARGET_SUBTARGET= \
                  .config 2>/dev/null \
         )"
        TARGET=${TARGET:-$CONFIG_TARGET_BOARD}
        SUBTARGET=${SUBTARGET:-$CONFIG_TARGET_SUBTARGET}
        [[ -n ${TARGET} ]] && echo "target=$TARGET" >> ${GITHUB_OUTPUT}
        [[ -n ${SUBTARGET} ]] && echo "subtarget=$SUBTARGET" >> ${GITHUB_OUTPUT}
        echo $TARGET/$SUBTARGET

  build:
    name: Build tools
    runs-on: ubuntu-latest
    needs: determine_targets
    env: 
      TARGET: ${{ needs.determine_targets.outputs.target }}
      SUBTARGET: ${{ needs.determine_targets.outputs.subtarget }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3      

      - name: Checkoutsrc
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_URL }}
          ref: ${{ env.REPO_BRANCH}}
          path: openwrt

      - name: Restore ccache cache
        id: restore-ccache-cache
        if: inputs.use_ccache_cache  
        uses: actions/cache/restore@v3
        with:
          path: openwrt/.ccache
          key: ccache-${{ env.TARGET }}-${{ env.SUBTARGET }}-external-toolchain-${{ hashFiles('openwrt/tools/**','openwrt/toolchain/**') }}
          restore-keys: |
            ccache-${{ env.TARGET }}-${{ env.SUBTARGET }}-external-toolchain-

      - name: Set global configs
        working-directory: openwrt
        run: |
          [[ -e ${GITHUB_WORKSPACE}/${CONFIG_FILE} ]] && cp -f ${GITHUB_WORKSPACE}/${CONFIG_FILE} .config
          echo CONFIG_DEVEL=y >> .config
          echo CONFIG_AUTOREMOVE=y >> .config
          # echo CONFIG_TARGET_${{ env.TARGET }}=y >> .config
          # echo CONFIG_TARGET_${{ env.TARGET }}_${{ env.SUBTARGET }}=y >> .config
          echo CONFIG_BUILD_ALL_HOST_TOOLS=y >> .config
                    
      - name: Configure ccache and apply fixes
        if: inputs.use_ccache_cache 
        working-directory: openwrt
        env:
          SYSTEM_CCACHE_CONF: staging_dir/host/etc/ccache.conf
        run: |
          mkdir -p staging_dir/host/etc
          touch $SYSTEM_CCACHE_CONF
          echo compiler_type=gcc >> $SYSTEM_CCACHE_CONF
          echo CONFIG_CCACHE=y >> .config

      - name: Cache prebuilt tools and toolchain
        uses: actions/cache@v3
        with:
          path: openwrt/tools.tar
          key: ${{ env.TARGET }}-${{ env.SUBTARGET }}-external-toolchain-${{ hashFiles('openwrt/tools/**','openwrt/toolchain/**') }}
          restore-keys: ${{ env.TARGET }}-${{ env.SUBTARGET }}-external-toolchain-

      - name: Make prereq
        working-directory: openwrt
        run: make defconfig
  
      - name: Show configuration
        working-directory: openwrt
        run: ./scripts/diffconfig.sh

      - name: Build tools 
        working-directory: openwrt
        run: make tools/install -j$(nproc) BUILD_LOG=1 || ret=$? ${GITHUB_WORKSPACE}/.github/workflows/scripts/show_build_failures.sh

      - name: Build toolchain
        working-directory: openwrt
        run: make toolchain/install -j$(nproc) BUILD_LOG=1 || ret=$? ${GITHUB_WORKSPACE}/.github/workflows/scripts/show_build_failures.sh

      - name: Build external toolchain
        working-directory: openwrt
        run: |
          make target/toolchain/compile -j$(nproc) BUILD_LOG=1 || ret=$? ${GITHUB_WORKSPACE}/.github/workflows/scripts/show_build_failures.sh
          TOOLCHAIN_NAME=$(ls bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }} | grep toolchain)
          echo "toolchain-name=$TOOLCHAIN_NAME" >> $GITHUB_ENV
          mkdir -p external-toolchain && cp -f bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/$TOOLCHAIN_NAME external-toolchain/$TOOLCHAIN_NAME

      - name: Package tools and external toolchain 
        working-directory: openwrt
        run: tar -cvf tools.tar staging_dir/host build_dir/host staging_dir/target-* external-toolchain

      - name: Upload prebuilt tools and external toolchain
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET }}-${{ env.SUBTARGET }}-external-toolchain
          path: openwrt/tools.tar

      - name: Upload logs
        if: ${{!cancelled()}}
        uses: actions/upload-artifact@v3
        with:
          name: linux-buildbot-logs
          path: openwrt/logs

      - name: Upload config
        if: ${{!cancelled()}}
        uses: actions/upload-artifact@v3
        with:
          name: linux-buildbot-config
          path: openwrt/.config
  
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
